import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const skins = JSON.parse(readFileSync(resolve(root, 'src/theme-skins/skins.json'), 'utf8'));

const clamp = (n) => Math.max(0, Math.min(255, Math.round(n)));

function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
}

const rgbToHex = ([r, g, b]) =>
  '#' + [r, g, b].map((v) => clamp(v).toString(16).padStart(2, '0')).join('');

function mix(hexA, hexB, t) {
  const a = hexToRgb(hexA);
  const b = hexToRgb(hexB);
  return rgbToHex(a.map((v, i) => v + (b[i] - v) * t));
}

const rgba = (hex, alpha) => {
  const [r, g, b] = hexToRgb(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
};

// ---- background effects --------------------------------
function effectVars(effect, accent) {
  const a = rgba(accent, 1);
  const [r, g, b] = hexToRgb(accent);
  const c = `${r}, ${g}, ${b}`;
  switch (effect) {
    case 'glow':
      return {
        '--bg-image': `radial-gradient(70rem 30rem at 50% -10%, rgba(${c}, 0.16), transparent 60%)`,
        '--bg-size': 'auto',
        '--bg-repeat': 'no-repeat',
        '--bg-position': 'center top',
      };
    case 'aurora':
      return {
        '--bg-image': `radial-gradient(42rem 26rem at 12% 8%, rgba(${c}, 0.10), transparent 55%), radial-gradient(46rem 30rem at 88% 20%, rgba(${c}, 0.08), transparent 55%), radial-gradient(60rem 34rem at 50% 110%, rgba(${c}, 0.06), transparent 60%)`,
        '--bg-size': 'auto',
        '--bg-repeat': 'no-repeat',
        '--bg-position': 'center top',
      };
    case 'grid':
      return {
        '--bg-image': `linear-gradient(rgba(${c}, 0.055) 1px, transparent 1px), linear-gradient(90deg, rgba(${c}, 0.055) 1px, transparent 1px)`,
        '--bg-size': '34px 34px',
        '--bg-repeat': 'repeat',
        '--bg-position': '0 0',
      };
    case 'dots':
      return {
        '--bg-image': `radial-gradient(rgba(${c}, 0.16) 1px, transparent 1.5px)`,
        '--bg-size': '26px 26px',
        '--bg-repeat': 'repeat',
        '--bg-position': '0 0',
      };
    case 'scan':
      return {
        '--bg-image': `repeating-linear-gradient(0deg, rgba(${c}, 0.045) 0 1px, transparent 1px 5px)`,
        '--bg-size': 'auto',
        '--bg-repeat': 'repeat',
        '--bg-position': '0 0',
      };
    case 'wash':
      return {
        '--bg-image': `linear-gradient(180deg, transparent 0%, rgba(${c}, 0.07) 100%)`,
        '--bg-size': 'auto',
        '--bg-repeat': 'no-repeat',
        '--bg-position': 'center bottom',
      };
    default:
      return {
        '--bg-image': 'none',
        '--bg-size': 'auto',
        '--bg-repeat': 'no-repeat',
        '--bg-position': 'center',
      };
  }
}

function darkBlock(skin) {
  const accent = mix(skin.accent, '#ffffff', 0.1);
  const bg = mix(skin.darkBase, skin.accent, 0.07);
  return {
    '--font-display': skin.font,
    '--background': bg,
    '--foreground': mix(bg, '#ffffff', 0.92),
    '--muted-foreground': mix(bg, '#ffffff', 0.58),
    '--text-body': mix(bg, '#ffffff', 0.74),
    '--text-strong': '#ffffff',
    '--text-em': mix(bg, '#ffffff', 0.84),
    '--accent': accent,
    '--accent-muted': rgba(accent, 0.15),
    '--border': mix(bg, '#ffffff', 0.14),
    '--surface': mix(bg, '#ffffff', 0.07),
    '--surface-raised': mix(bg, '#ffffff', 0.11),
    '--card-bg': mix(bg, '#000000', 0.04),
    '--header-bg': rgba(bg, 0.85),
    '--code-bg': mix(bg, '#000000', 0.07),
    '--code-header': mix(bg, '#000000', 0.02),
    '--shadow-card': '0 12px 30px rgba(0, 0, 0, 0.4)',
    ...effectVars(skin.effect, accent),
  };
}

function lightBlock(skin) {
  const accent = mix(skin.accent, '#000000', 0.2);
  const bg = mix(skin.lightBase, skin.accent, 0.045);
  return {
    '--font-display': skin.font,
    '--background': bg,
    '--foreground': mix(bg, '#000000', 0.92),
    '--muted-foreground': mix(bg, '#000000', 0.6),
    '--text-body': mix(bg, '#000000', 0.74),
    '--text-strong': '#09090b',
    '--text-em': mix(bg, '#000000', 0.82),
    '--accent': accent,
    '--accent-muted': rgba(accent, 0.12),
    '--border': mix(bg, '#000000', 0.14),
    '--surface': mix(bg, '#ffffff', 0.55),
    '--surface-raised': '#ffffff',
    '--card-bg': '#ffffff',
    '--header-bg': rgba(bg, 0.85),
    '--code-bg': mix(bg, '#000000', 0.025),
    '--code-header': mix(bg, '#000000', 0.05),
    '--shadow-card': '0 10px 25px rgba(0, 0, 0, 0.08)',
    ...effectVars(skin.effect, accent),
  };
}

function cssBlock(selector, vars) {
  const lines = Object.entries(vars).map(([k, v]) => `  ${k}: ${v};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

let out = '/* Generated by scripts/generate-themes.mjs — do not edit by hand. */\n';
out += '/* Re-run: node scripts/generate-themes.mjs */\n\n';
for (const skin of skins) {
  out += cssBlock(`:root[data-skin="${skin.id}"]`, darkBlock(skin));
  out += `\n${cssBlock(`:root[data-skin="${skin.id}"][data-theme="light"]`, lightBlock(skin))}\n`;
}

const dest = resolve(root, 'src/styles/themes.css');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out, 'utf8');
console.log(`Wrote ${dest} (${skins.length} skins, ${out.split('\n').length} lines)`);